spring.application.name=payment-orchestrator

server.port=10005
server.shutdown=graceful
server.servlet.context-path=/

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/payment_orchestrator}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:10005,http://127.0.0.1:10005,https://lalitbodana236.github.io}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2s

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.probes.enabled=true
management.endpoints.web.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:10005,http://127.0.0.1:10005,https://lalitbodana236.github.io}
management.endpoints.web.cors.allowed-methods=GET,POST,OPTIONS
management.endpoints.web.cors.allowed-headers=*
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}

springdoc.api-docs.path=/v3/api-docs

payment.orchestration.retry.max-attempts=3
payment.orchestration.retry.initial-interval-ms=200
payment.orchestration.retry.multiplier=2.0
payment.orchestration.retry.max-interval-ms=2000
payment.orchestration.idempotency.ttl-hours=24
payment.orchestration.idempotency.lock-ttl-seconds=15
payment.orchestration.idempotency.wait-timeout-ms=3000
payment.orchestration.idempotency.poll-interval-ms=100
payment.orchestration.provider.timeout-ms=1500

resilience4j.circuitbreaker.instances.PROVIDER_A.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.PROVIDER_A.sliding-window-size=10
resilience4j.circuitbreaker.instances.PROVIDER_A.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.PROVIDER_A.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.PROVIDER_A.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.PROVIDER_B.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.PROVIDER_B.sliding-window-size=10
resilience4j.circuitbreaker.instances.PROVIDER_B.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.PROVIDER_B.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.PROVIDER_B.wait-duration-in-open-state=10s
